# Site settings
title: etff wiki
url: "https://etff.github.io"
baseurl: ""
description: >
    배운 것을 기록하는 위키

# My information
email:
author: etff
profile:
twitter_username:
github_username: etff
comment-support: giscus

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
# repo_id, category_id 는 GitHub GraphQL API 로 조회한 값이다.
#   gh api graphql -f query='query{repository(owner:"etff",name:"etff.github.io"){
#     id discussionCategories(first:20){nodes{id name}}}}'
giscus:
  repo: etff/etff.github.io
  repo_id: R_kgDOJYVRag
  category: Announcements
  category_id: DIC_kwDOJYVRas4DDEcO

google_analytics:
  ua:
  encrypted_ua:

google_adsense:
  client:

blame: "https://github.com/etff/etff.github.io/blame/master/_wiki"
edit: "https://github.com/etff/etff.github.io/edit/master/_wiki"
issue: "https://github.com/etff/etff.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html
kramdown:
    input: GFM
    syntax_highlighter: rouge
    smart_quotes: ["apos", "apos", "quot", "quot"]
